apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx2
  name: mynginx2
spec:
  containers:
  - image: public.ecr.aws/l3x6e3t5/takima-training/nginx
    name: mynginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
